### ISSUE TITLE
How to Build

### ISSUE THREAD

**Issue by alexander-schoch-github** [aPixelInSpace/F-a-maze-ing#5]
Amazing project!

One problem though: How do you build this from source?

**Comment by aPixelInSpace** [comment]
Thanks :)

I'll add a build section in the readme and the wiki.
But in short, you'll need the last dotnet sdk available here https://dotnet.microsoft.com/download/dotnet/5.0
After you cloned the project from Github, just navigate to the root folder (where the f-a-maze-ing.sln file is) and run the command "dotnet build". It should restore all dependencies and compile everything.

**Comment by aPixelInSpace** [comment]
I updated the wiki https://github.com/aPixelInSpace/F-a-maze-ing/wiki#build
