### ISSUE TITLE
Web page needs horizontal scrollbar

### ISSUE THREAD

**Issue by fire-eggs** [aPixelInSpace/F-a-maze-ing#6]
When generating random mazes on the demo site, it's possible to get a wide maze. There is no horizontal scrollbar in that case. Nor some alternate way to see the full maze (e.g. drag w/ mouse).

[Using Brave (Chrome) on Linux]

Otherwise, quite entertaining!

**Comment by aPixelInSpace** [comment]
Thanks :)

I'll fix this issue.

**Comment by aPixelInSpace** [comment]
I added a horizontal scrollbar (the fix was relatively easy), so it should be ok now. You may have to delete the browser cache.
