### ISSUE TITLE
I can't generate solution

### ISSUE THREAD

**Issue by vienduong88** [aPixelInSpace/F-a-maze-ing#8]
I can't use the "-s" to generate solution. I wrote like this :

Mazes.exe s-rectangle -r 6 -c 10 : g-ortho : a-hk -s 2 : rs-ortho -d -e -s : o-file -p "./output/test2.svg"

It pulls out a file with maze & depth color but no solution.

Am I doing anything wrong here?
Thank you.

**Comment by aPixelInSpace** [comment]
Hi !

I used the same command as you and it _does_ generate the solution. That is strange. How do you visualize the resulting SVG file ? Do you use Chrome or something else (in that case could try with Chrome) ?

Thank you

**Comment by vienduong88** [comment]
Hello.

I try viewing it in chrome and it's actually show the solution. I used Illustrator before and it shows something like this

(https://user-images.githubusercontent.com/33787514/125191138-0e0c5780-e26b-11eb-82de-a5d754def45e.png)

Thank you for your reply!

**Comment by aPixelInSpace** [comment]
All right !

I'll close the issue.

Thank you !
